[govctl]
schema = 1
id = "ADR-0001"
title = "Use UV for project management"
status = "accepted"
date = "2026-01-23"

[content]
context = """
The project needs a way to manage dependencies
convieniently and reliable."""
decision = "Use UV for project management."
consequences = """
Positive: Easier to work with than without project manager. Better than other project managers.
Negative: None
"""
